# Generated by Django 2.1.15 on 2020-07-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userEmail',
        ),
    ]
