# Generated by Django 2.1.15 on 2020-07-27 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200724_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='taste3',
        ),
    ]
