# Generated by Django 2.1.15 on 2020-07-28 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_taste3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Intro',
            new_name='intro',
        ),
    ]
