# Generated by Django 2.1.15 on 2020-08-07 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='image_first',
            new_name='image_A',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='image_second',
            new_name='image_B',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_first',
            new_name='topic_A',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_second',
            new_name='topic_B',
        ),
    ]
