# Generated by Django 2.1.15 on 2020-08-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0002_auto_20200807_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vs_comment',
            name='select',
            field=models.CharField(max_length=10),
        ),
    ]
