# Generated by Django 2.1.15 on 2020-08-11 02:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versus', '0002_auto_20200810_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='select_A',
            field=models.ManyToManyField(blank=True, related_name='selectASet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='select_B',
            field=models.ManyToManyField(blank=True, related_name='selectBSet', to=settings.AUTH_USER_MODEL),
        ),
    ]
