# Generated by Django 2.1.15 on 2020-08-08 13:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versus', '0003_auto_20200808_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='select_A',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='select_B',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.AddField(
            model_name='topic',
            name='select_A',
            field=models.ManyToManyField(related_name='selectASet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='select_B',
            field=models.ManyToManyField(related_name='selectBSet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
