# Generated by Django 2.1.15 on 2020-07-23 06:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='articleContent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='articleCreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='articleHashTag',
            new_name='hashTag',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='articleImage',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='articleUpdatedAt',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentContent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentCreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commentUpdatedAt',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='recomment',
            old_name='recommentContent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='recomment',
            old_name='recommentCreatedAt',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='recomment',
            old_name='recommentUpdatedAt',
            new_name='updatedAt',
        ),
        migrations.AlterField(
            model_name='article',
            name='scrap',
            field=models.ManyToManyField(related_name='scrapSet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like',
            field=models.ManyToManyField(related_name='commentLikeSet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='like',
            field=models.ManyToManyField(related_name='recommentLikeSet', to=settings.AUTH_USER_MODEL),
        ),
    ]
