# Generated by Django 2.1.15 on 2020-07-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200723_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='hashTag',
        ),
        migrations.AddField(
            model_name='article',
            name='hashtag',
            field=models.ManyToManyField(related_name='hashtagSet', to='articles.Hashtag'),
        ),
    ]
