# Generated by Django 2.1.15 on 2020-07-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200723_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='base64',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
