# Generated by Django 2.1.15 on 2020-07-28 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200729_0151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='base64',
        ),
    ]
