# Generated by Django 2.1.15 on 2020-07-29 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200729_1135'),
        ('articles', '0004_remove_article_base64'),
    ]

    operations = [
    ]
